/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set speed (0 = pause; the last non-zero speed is remembered) */
        post: operations["set_speed_api_speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual sale (works while paused) */
        post: operations["sell_api_sell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a product (logged as EDIT, saved to CSV at once) */
        patch: operations["edit_product_api_products__product_id__patch"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change settings (logged as SETTINGS_CHANGED) */
        post: operations["update_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load a scenario: new run, orders cleared, sim_s and counters reset */
        post: operations["load_scenario_api_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload the current scenario (new run, logged as RESET) */
        post: operations["reset_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curveballs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Curveball presets */
        get: operations["list_curveballs_api_curveballs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curveball": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tell the agent some news (a preset also changes the world) */
        post: operations["add_curveball_api_curveball_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock history of one product in the current run */
        get: operations["history_api_history__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live snapshot stream (SSE)
         * @description Server-Sent Events. Each message's data is the same `Snapshot` JSON as `GET /api/snapshot`, sent every tick (0.5s). A `: heartbeat` comment is sent every 15s.
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentPlan
         * @description The latest Gemini decision (or its fallback), for the plan card. Memory only.
         */
        AgentPlan: {
            /** Sim S */
            sim_s: number;
            /** Shop Time */
            shop_time: string;
            /** Trigger */
            trigger: string;
            /** Situation */
            situation: string;
            /** Steps */
            steps: components["schemas"]["PlanStep"][];
        };
        /**
         * AgentStatus
         * @description Live agent view (in memory only; part of the phase 4 Snapshot).
         */
        AgentStatus: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "gemini";
            /** Enabled */
            enabled: boolean;
            /**
             * Thinking
             * @default false
             */
            thinking: boolean;
            /**
             * Llm Ready
             * @default false
             */
            llm_ready: boolean;
            /** Last Latency Ms */
            last_latency_ms?: number | null;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Fallbacks
             * @default 0
             */
            fallbacks: number;
            /**
             * Calls Last 60S
             * @default 0
             */
            calls_last_60s: number;
            /**
             * Call Limit
             * @default 10
             */
            call_limit: number;
            /**
             * Next Call Allowed In S
             * @default 0
             */
            next_call_allowed_in_s: number;
            /** Pending Products */
            pending_products?: string[];
            plan?: components["schemas"]["AgentPlan"] | null;
        };
        /** Counters */
        Counters: {
            /**
             * Sales
             * @default 0
             */
            sales: number;
            /**
             * Missed Sales
             * @default 0
             */
            missed_sales: number;
            /**
             * Orders Placed
             * @default 0
             */
            orders_placed: number;
            /**
             * Extra Fees
             * @default 0
             */
            extra_fees: number;
        };
        /** CurveballPreset */
        CurveballPreset: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Effect */
            effect: string;
        };
        /**
         * CurveballRequest
         * @description Exactly one of preset or text.
         */
        CurveballRequest: {
            /** Preset */
            preset?: string | null;
            /** Text */
            text?: string | null;
        };
        /** CurveballView */
        CurveballView: {
            /** Id */
            id: number;
            /** Preset */
            preset: string | null;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Seconds Left */
            seconds_left: number;
        };
        /** Event */
        Event: {
            /** Run Id */
            run_id: number;
            /**
             * Ts Real
             * Format: date-time
             */
            ts_real: string;
            /** Sim S */
            sim_s: number;
            /** Shop Time */
            shop_time: string;
            type: components["schemas"]["EventType"];
            /** Product Id */
            product_id?: string | null;
            /** Qty */
            qty?: number | null;
            /** Stock After */
            stock_after?: number | null;
            /**
             * Ref
             * @default
             */
            ref: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "SALE" | "MISSED_SALE" | "CROSSED_MARK" | "ORDER_PLACED" | "ORDER_CONFIRMED" | "ORDER_SHIPPED" | "DELIVERED" | "EDIT" | "SETTINGS_CHANGED" | "SCENARIO_LOADED" | "RESET" | "AGENT_WAIT" | "AGENT_FALLBACK" | "CURVEBALL";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** History */
        History: {
            /** Product Id */
            product_id: string;
            /** Window S */
            window_s: number;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /** Markers */
            markers: components["schemas"]["HistoryMarker"][];
            /** Shadow Points */
            shadow_points: components["schemas"]["HistoryPoint"][];
        };
        /** HistoryMarker */
        HistoryMarker: {
            /**
             * Type
             * @enum {string}
             */
            type: "ORDER_PLACED" | "DELIVERED";
            /** Sim S */
            sim_s: number;
            /** Shop Time */
            shop_time: string;
            /** Qty */
            qty: number | null;
            /** Stock After */
            stock_after: number | null;
            /** Ref */
            ref: string;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Sim S */
            sim_s: number;
            /** Shop Time */
            shop_time: string;
            /** Stock After */
            stock_after: number;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "PLACED" | "CONFIRMED" | "SHIPPED" | "DELIVERED";
        /** OrderView */
        OrderView: {
            /** Id */
            id: string;
            /** Product Id */
            product_id: string;
            /** Qty */
            qty: number;
            /** @default PLACED */
            status: components["schemas"]["OrderStatus"];
            /** Placed At S */
            placed_at_s: number;
            /** Due At S */
            due_at_s: number;
            /** Delivered At S */
            delivered_at_s?: number | null;
            /**
             * Supplier
             * @default main
             * @enum {string}
             */
            supplier: "main" | "backup";
            /** Product Name */
            product_name: string;
            /** Seconds Left */
            seconds_left: number;
        };
        /** PlanStep */
        PlanStep: {
            /** Product Id */
            product_id: string;
            /** Product Name */
            product_name: string;
            /**
             * Action
             * @enum {string}
             */
            action: "order" | "wait";
            /** Qty */
            qty: number;
            /**
             * Supplier
             * @enum {string}
             */
            supplier: "main" | "backup";
            /** Reason */
            reason: string;
            /**
             * Source
             * @enum {string}
             */
            source: "rules" | "gemini" | "fallback";
        };
        /**
         * ProductPatch
         * @description Every field optional; limits are checked on the product AFTER merging (Product validators).
         */
        ProductPatch: {
            /** Stock */
            stock?: number | null;
            /** Max Stock */
            max_stock?: number | null;
            /** Reorder Point */
            reorder_point?: number | null;
            /** Sell Weight */
            sell_weight?: number | null;
            /** Lead Time S */
            lead_time_s?: number | null;
        };
        /** ProductView */
        ProductView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Stock */
            stock: number;
            /** Max Stock */
            max_stock: number;
            /** Reorder Point */
            reorder_point: number;
            /** Sell Weight */
            sell_weight: number;
            /** Lead Time S */
            lead_time_s: number;
            /**
             * State
             * @enum {string}
             */
            state: "EMPTY" | "AWAITING" | "DANGER" | "RESTOCKED" | "SELLING";
            /** Badge */
            badge?: string | null;
            /** Badge Kind */
            badge_kind?: ("arriving" | "agent" | "delivered") | null;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /** Name */
            name: string;
        };
        /** Score */
        Score: {
            /** Missed Sales */
            missed_sales: number;
            /** Lost Profit */
            lost_profit: number;
            /** Extra Fees */
            extra_fees: number;
            /** Total Cost */
            total_cost: number;
        };
        /**
         * Scoreboard
         * @description The real shop (agent) against the shadow shop (rules), same customers.
         */
        Scoreboard: {
            agent: components["schemas"]["Score"];
            rules: components["schemas"]["Score"];
            /** Agent Ahead By */
            agent_ahead_by: number;
            /** Same Brain */
            same_brain: boolean;
        };
        /** SellRequest */
        SellRequest: {
            /** Product Id */
            product_id: string;
            /**
             * Qty
             * @default 1
             */
            qty: number;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Rush Hour */
            rush_hour?: boolean | null;
            /** Supplier Delay */
            supplier_delay?: boolean | null;
            /** Agent Enabled */
            agent_enabled?: boolean | null;
            /** Agent Mode */
            agent_mode?: ("rules" | "gemini") | null;
            /** Agent Interval S */
            agent_interval_s?: number | null;
        };
        /**
         * SimSettings
         * @description User-changeable settings (POST /api/settings).
         *
         *     Named SimSettings to avoid clashing with config.Settings.
         */
        SimSettings: {
            /**
             * Rush Hour
             * @default false
             */
            rush_hour: boolean;
            /**
             * Supplier Delay
             * @default false
             */
            supplier_delay: boolean;
            /**
             * Agent Enabled
             * @default true
             */
            agent_enabled: boolean;
            /**
             * Agent Mode
             * @default rules
             * @enum {string}
             */
            agent_mode: "rules" | "gemini";
            /**
             * Agent Interval S
             * @default 5
             */
            agent_interval_s: number;
        };
        /**
         * Snapshot
         * @description Everything the screen shows; also the SSE payload. React only formats it.
         */
        Snapshot: {
            /** Run Id */
            run_id: number;
            /** Sim S */
            sim_s: number;
            /** Shop Time */
            shop_time: string;
            /**
             * Speed
             * @enum {unknown}
             */
            speed: 0 | 0.5 | 1 | 5;
            /**
             * Last Speed
             * @enum {unknown}
             */
            last_speed: 0.5 | 1 | 5;
            /** Scenario */
            scenario: string;
            settings: components["schemas"]["SimSettings"];
            counters: components["schemas"]["Counters"];
            /** Orders On The Way */
            orders_on_the_way: number;
            /** Next Agent Check S */
            next_agent_check_s: number;
            /** Saved Ago S */
            saved_ago_s: number | null;
            /** Products */
            products: components["schemas"]["ProductView"][];
            /** Orders */
            orders: components["schemas"]["OrderView"][];
            /** Events */
            events: components["schemas"]["Event"][];
            agent: components["schemas"]["AgentStatus"];
            /** Curveballs */
            curveballs: components["schemas"]["CurveballView"][];
            scoreboard: components["schemas"]["Scoreboard"];
            /** Shadow Stock */
            shadow_stock: {
                [key: string]: number;
            };
        };
        /** SpeedRequest */
        SpeedRequest: {
            /**
             * Speed
             * @enum {unknown}
             */
            speed: 0 | 0.5 | 1 | 5;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    set_speed_api_speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sell_api_sell_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_product_api_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    load_scenario_api_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    list_curveballs_api_curveballs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurveballPreset"][];
                };
            };
        };
    };
    add_curveball_api_curveball_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurveballRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history__product_id__get: {
        parameters: {
            query?: {
                /** @description Sim seconds to look back */
                window_s?: number;
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
}
